version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    # environment:
    #   # Database connection
    #   - DATABASE_URL=${DATABASE_URL}
      
    #   # Server configuration
    #   - NODE_ENV=${NODE_ENV}
    #   - PORT=${PORT}
      
    #   # URLs
    #   - FRONTEND_URL=${FRONTEND_URL}
    #   - API_URL=${API_URL}
    #   - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      
    #   # Authentication
    #   - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
    #   - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
    #   - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    env_file:
      - .env 
    ports:
      - "${PORT}:${PORT}"
    # No db dependency since using external database
    restart: always

  # Local database - commented out since you're using an external one
  # Uncomment this section if you want to switch to a local database
  # db:
  #   image: postgres:15
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER:-postgres}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
  #     - POSTGRES_DB=${POSTGRES_DB:-frens}
  #   ports:
  #     - "${DB_PORT:-5432}:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

# Uncomment this when using the local database
# volumes:
#   postgres-data:
